using System;
using System.Runtime.InteropServices;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_sysfontinfo.h

namespace PdfLibCore.Generated.Structs;
// Struct: FPDF_CharsetFontMap
// Provides the name of a font to use for a given charset value.
[StructLayout(LayoutKind.Sequential)]
public partial struct FPDF_CHARSETFONTMAP
{
    // Character Set Enum value, see FXFONT_*_CHARSET above.
    public int Charset { get; set; }

    // Name of default font to use with that charset.
    public string Fontname { get; set; }
}