using System;
using System.Runtime.InteropServices;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (08:37:23) - Utc
// DO NOT MODIFY
// Sourcefile: fpdfview.h

namespace PdfLibCore.Generated.Structs;
// Structure for file reading or writing (I/O).
// Note: This is a handler and should be implemented by callers,
// and is only used from XFA.
[StructLayout(LayoutKind.Sequential)]
public partial struct FPDF_FILEHANDLER
{
    // User-defined data.
    // Note: Callers can use this field to track controls.
    public IntPtr ClientData { get; set; }
}