using System;
using System.Runtime.InteropServices;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (08:37:23) - Utc
// DO NOT MODIFY
// Sourcefile: fpdfview.h

namespace PdfLibCore.Generated.Structs;
// Process-wide options for initializing the library.
[StructLayout(LayoutKind.Sequential)]
public partial struct FPDF_LIBRARY_CONFIG
{
    // Version number of the interface. Currently must be 2.
    // Support for version 1 will be deprecated in the future.
    public int Version { get; set; }

    // Array of paths to scan in place of the defaults when using built-in
    // FXGE font loading code. The array is terminated by a NULL pointer.
    // The Array may be NULL itself to use the default paths. May be ignored
    // entirely depending upon the platform.
    public string UserFontPaths { get; set; }

    // Pointer to the v8::Isolate to use, or NULL to force PDFium to create one.
    public IntPtr Isolate { get; set; }

    // The embedder data slot to use in the v8::Isolate to store PDFium's
    // per-isolate data. The value needs to be in the range
    // [0, |v8::Internals::kNumIsolateDataLots|). Note that 0 is fine for most
    // embedders.
    public uint V8EmbedderSlot { get; set; }

    // Pointer to the V8::Platform to use.
    public IntPtr Platform { get; set; }
}