using System;
using System.Runtime.InteropServices;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/fpdfview.h

namespace PdfLibCore.Generated.Structs;
// Struct for color scheme.
// Each should be a 32-bit value specifying the color, in 8888 ARGB format.
[StructLayout(LayoutKind.Sequential)]
public partial struct FPDF_COLORSCHEME
{
    public uint PathFillColor { get; set; }

    public uint PathStrokeColor { get; set; }

    public uint TextFillColor { get; set; }

    public uint TextStrokeColor { get; set; }
}