using System;
using System.Runtime.InteropServices;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (08:37:23) - Utc
// DO NOT MODIFY
// Sourcefile: fpdfview.h

namespace PdfLibCore.Generated.Structs;
// 2D Point. Coordinate system agnostic.
[StructLayout(LayoutKind.Sequential)]
public partial struct FS_POINTF
{
    public float X { get; set; }

    public float Y { get; set; }
}