using System;
using System.Runtime.InteropServices;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h

namespace PdfLibCore.Generated.Structs;
[StructLayout(LayoutKind.Sequential)]
public partial struct FS_QUADPOINTSF
{
    public float X1 { get; set; }

    public float Y1 { get; set; }

    public float X2 { get; set; }

    public float Y2 { get; set; }

    public float X3 { get; set; }

    public float Y3 { get; set; }

    public float X4 { get; set; }

    public float Y4 { get; set; }
}