using System;
using System.Runtime.InteropServices;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/fpdfview.h

namespace PdfLibCore.Generated.Structs;
// Rectangle area(float) in device or page coordinate system.
[StructLayout(LayoutKind.Sequential)]
public partial struct FS_RECTF
{
    // The x-coordinate of the left-top corner.
    public float Left { get; set; }

    // The y-coordinate of the left-top corner.
    public float Top { get; set; }

    // The x-coordinate of the right-bottom corner.
    public float Right { get; set; }

    // The y-coordinate of the right-bottom corner.
    public float Bottom { get; set; }
}