using System;
using System.Runtime.InteropServices;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h

namespace PdfLibCore.Generated.Structs;
// Interface for checking whether sections of the file are available.
[StructLayout(LayoutKind.Sequential)]
public partial struct FX_FILEAVAIL
{
    // Version number of the interface. Must be 1.
    public int Version { get; set; }
}