Classes:
  FPDF_LIBRARY_CONFIG_:
    Properties:
      m_pUserFontPaths:
        Ignore: true

Methods:
  FPDF_GetFileVersion:
    Parameters:
      fileVersion:
        Usage: Out

  FPDF_GetPageSizeByIndex:
    Parameters:
      width:
        Usage: Out
      height:
        Usage: Out

  FPDF_DeviceToPage:
    Parameters:
      page_x:
        Usage: Out
      page_y:
        Usage: Out

  FPDF_PageToDevice:
    Parameters:
      device_x:
        Usage: Out
      device_y:
        Usage: Out

  FPDF_GetNamedDest:
    Parameters:
      buflen:
        Usage: Out

  FPDFDest_GetView:
    Parameters:
      pNumParams:
        Usage: Out

  FPDFDest_GetLocationInPage:
    Parameters:
      hasXVal:
        Usage: Out
      hasYVal:
        Usage: Out
      hasZoomVal:
        Usage: Out
      x:
        Usage: Out
      y:
        Usage: Out
      zoom:
        Usage: Out

  FPDFLink_Enumerate:
    Parameters:
      linkAnnot:
        Usage: Out

  FPDFLink_GetAnnotRect:
    Parameters:
      rect:
        Usage: Out

  FPDFLink_GetQuadPoints:
    Parameters:
      quadPoints:
        Usage: Out

  FPDFPageObjMark_GetName:
    Parameters:
      out_buflen:
        Usage: Out

  FPDFPageObjMark_GetParamKey:
    Parameters:
      out_buflen:
        Usage: Out

  FPDFPageObjMark_GetParamIntValue:
    Parameters:
      out_buflen:
        Usage: Out

  FPDFPageObjMark_GetParamStringValue:
    Parameters:
      out_buflen:
        Usage: Out

  FPDFPageObjMark_GetParamBlobValue:
    Parameters:
      out_buflen:
        Usage: Out

  FPDFImageObj_GetMatrix:
    Parameters:
      a:
        Usage: Out
      b:
        Usage: Out
      c:
        Usage: Out
      d:
        Usage: Out
      e:
        Usage: Out
      f:
        Usage: Out

  FPDFImageObj_GetImageMetadata:
    Parameters:
      metadata:
        Usage: Out

  FPDFPageObj_GetBounds:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFPageObj_GetStrokeColor:
    Parameters:
      R:
        Usage: Out
      G:
        Usage: Out
      B:
        Usage: Out
      A:
        Usage: Out

  FPDFPageObj_GetStrokeWidth:
    Parameters:
      width:
        Usage: Out

  FPDFPageObj_GetFillColor:
    Parameters:
      R:
        Usage: Out
      G:
        Usage: Out
      B:
        Usage: Out
      A:
        Usage: Out

  FPDFPathSegment_GetPoint:
    Parameters:
      x:
        Usage: Out
      y:
        Usage: Out

  FPDFPath_GetDrawMode:
    Parameters:
      fillMode:
        Usage: Out
      stroke:
        Usage: Out

  FPDFText_GetFontInfo:
    Parameters:
      flags:
        Usage: Out

  FPDFText_GetFillColor:
    Parameters:
      R:
        Usage: Out
      G:
        Usage: Out
      B:
        Usage: Out
      A:
        Usage: Out

  FPDFText_GetStrokeColor:
    Parameters:
      R:
        Usage: Out
      G:
        Usage: Out
      B:
        Usage: Out
      A:
        Usage: Out

  FPDFText_GetCharBox:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFText_GetCharOrigin:
    Parameters:
      x:
        Usage: Out
      y:
        Usage: Out

  FPDFText_GetRect:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFLink_GetRect:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFLink_GetTextRange:
    Parameters:
      start_char_index:
        Usage: Out
      char_count:
        Usage: Out

  FPDFPage_GetMediaBox:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFPage_GetCropBox:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFPage_GetBleedBox:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFPage_GetTrimBox:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFPage_GetArtBox:
    Parameters:
      left:
        Usage: Out
      bottom:
        Usage: Out
      right:
        Usage: Out
      top:
        Usage: Out

  FPDFBitmap_FillRect:
    Parameters:
      color:
        Type: FPDF_COLOR

  FPDFBookmark_Find:
    Parameters:
      title:
        Usage: In

  FPDF_GetLastError:
    ReturnType: FPDF_ERR

  FPDF_GetPageSizeByIndexF:
    Parameters:
      size:
        Usage: Out