/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (08:37:23) - Utc
// DO NOT MODIFY
// Sourcefile: fpdf_doc.h

namespace PdfLibCore.Generated.Enums;
public enum FPDF_FILEIDTYPE
{
    FILEIDTYPE_PERMANENT = 0,
    FILEIDTYPE_CHANGING = 1
}