/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/

namespace PdfLibCore.Generated.Enums;
public enum FPDF_ERR
{
    FPDF_ERR_SUCCESS = 0,
    FPDF_ERR_UNKNOWN = 1,
    FPDF_ERR_FILE = 2,
    FPDF_ERR_FORMAT = 3,
    FPDF_ERR_PASSWORD = 4,
    FPDF_ERR_SECURITY = 5,
    FPDF_ERR_PAGE = 6
}