/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/

namespace PdfLibCore.Generated.Enums;
public enum FPDF_OBJECT
{
    FPDF_OBJECT_UNKNOWN = 0,
    FPDF_OBJECT_BOOLEAN = 1,
    FPDF_OBJECT_NUMBER = 2,
    FPDF_OBJECT_STRING = 3,
    FPDF_OBJECT_NAME = 4,
    FPDF_OBJECT_ARRAY = 5,
    FPDF_OBJECT_DICTIONARY = 6,
    FPDF_OBJECT_STREAM = 7,
    FPDF_OBJECT_NULLOBJ = 8,
    FPDF_OBJECT_REFERENCE = 9
}