/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/

namespace PdfLibCore.Generated.Enums;
public enum FPDF_UNSP
{
    FPDF_UNSP_DOC_XFAFORM = 1,
    FPDF_UNSP_DOC_PORTABLECOLLECTION = 2,
    FPDF_UNSP_DOC_ATTACHMENT = 3,
    FPDF_UNSP_DOC_SECURITY = 4,
    FPDF_UNSP_DOC_SHAREDREVIEW = 5,
    FPDF_UNSP_DOC_SHAREDFORM_ACROBAT = 6,
    FPDF_UNSP_DOC_SHAREDFORM_FILESYSTEM = 7,
    FPDF_UNSP_DOC_SHAREDFORM_EMAIL = 8,
    FPDF_UNSP_ANNOT_3DANNOT = 11,
    FPDF_UNSP_ANNOT_MOVIE = 12,
    FPDF_UNSP_ANNOT_SOUND = 13,
    FPDF_UNSP_ANNOT_SCREEN_MEDIA = 14,
    FPDF_UNSP_ANNOT_SCREEN_RICHMEDIA = 15,
    FPDF_UNSP_ANNOT_ATTACHMENT = 16,
    FPDF_UNSP_ANNOT_SIG = 17
}