/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/

namespace PdfLibCore.Generated.Enums;
public enum FPDF_PRINTMODE
{
    FPDF_PRINTMODE_EMF = 0,
    FPDF_PRINTMODE_TEXTONLY = 1,
    FPDF_PRINTMODE_POSTSCRIPT2 = 2,
    FPDF_PRINTMODE_POSTSCRIPT3 = 3,
    FPDF_PRINTMODE_POSTSCRIPT2_PASSTHROUGH = 4,
    FPDF_PRINTMODE_POSTSCRIPT3_PASSTHROUGH = 5,
    FPDF_PRINTMODE_EMF_IMAGE_MASKS = 6,
    FPDF_PRINTMODE_POSTSCRIPT3_TYPE42 = 7,
    FPDF_PRINTMODE_POSTSCRIPT3_TYPE42_PASSTHROUGH = 8
}