/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/

namespace PdfLibCore.Generated.Enums;
public enum FPDF_COLORSPACE
{
    FPDF_COLORSPACE_UNKNOWN = 0,
    FPDF_COLORSPACE_DEVICEGRAY = 1,
    FPDF_COLORSPACE_DEVICERGB = 2,
    FPDF_COLORSPACE_DEVICECMYK = 3,
    FPDF_COLORSPACE_CALGRAY = 4,
    FPDF_COLORSPACE_CALRGB = 5,
    FPDF_COLORSPACE_LAB = 6,
    FPDF_COLORSPACE_ICCBASED = 7,
    FPDF_COLORSPACE_SEPARATION = 8,
    FPDF_COLORSPACE_DEVICEN = 9,
    FPDF_COLORSPACE_INDEXED = 10,
    FPDF_COLORSPACE_PATTERN = 11
}