/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/

namespace PdfLibCore.Generated.Enums;
public enum PDFACTION
{
    PDFACTION_UNSUPPORTED = 0,
    PDFACTION_GOTO = 1,
    PDFACTION_REMOTEGOTO = 2,
    PDFACTION_URI = 3,
    PDFACTION_LAUNCH = 4,
    PDFACTION_EMBEDDEDGOTO = 5
}