/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY
// Sourcefile: https://pdfium.googlesource.com/pdfium/+/master/public/

namespace PdfLibCore.Generated.Enums;
public enum PDFDEST_VIEW
{
    PDFDEST_VIEW_UNKNOWN_MODE = 0,
    PDFDEST_VIEW_XYZ = 1,
    PDFDEST_VIEW_FIT = 2,
    PDFDEST_VIEW_FITH = 3,
    PDFDEST_VIEW_FITV = 4,
    PDFDEST_VIEW_FITR = 5,
    PDFDEST_VIEW_FITB = 6,
    PDFDEST_VIEW_FITBH = 7,
    PDFDEST_VIEW_FITBV = 8
}