using System;
using System.Security;
using System.Runtime.InteropServices;
using PdfLibCore.Generated.Enums;
using PdfLibCore.Generated.Structs;
using PdfLibCore.Generated.Types;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY

namespace PdfLibCore.Generated;
public static partial class PlatformInvoke
{
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAvail_Create), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_AVAIL FPDFAvail_Create(ref FX_FILEAVAIL file_avail, ref FPDF_FILEACCESS file);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAvail_Destroy), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFAvail_Destroy(FPDF_AVAIL avail);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAvail_IsDocAvail), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAvail_IsDocAvail(FPDF_AVAIL avail, ref FX_DOWNLOADHINTS hints);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAvail_GetDocument), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_DOCUMENT FPDFAvail_GetDocument(FPDF_AVAIL avail, FPDF_BYTESTRING password);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAvail_GetFirstPageNum), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAvail_GetFirstPageNum(FPDF_DOCUMENT doc);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAvail_IsPageAvail), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAvail_IsPageAvail(FPDF_AVAIL avail, int page_index, ref FX_DOWNLOADHINTS hints);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAvail_IsFormAvail), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAvail_IsFormAvail(FPDF_AVAIL avail, ref FX_DOWNLOADHINTS hints);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_dataavail.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAvail_IsLinearized), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAvail_IsLinearized(FPDF_AVAIL avail);
}