using System;
using System.Security;
using System.Runtime.InteropServices;
using PdfLibCore.Generated.Enums;
using PdfLibCore.Generated.Structs;
using PdfLibCore.Generated.Types;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY

namespace PdfLibCore.Generated;
public static partial class PlatformInvoke
{
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_javascript.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDoc_GetJavaScriptActionCount), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFDoc_GetJavaScriptActionCount(FPDF_DOCUMENT document);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_javascript.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDoc_GetJavaScriptAction), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_JAVASCRIPT_ACTION FPDFDoc_GetJavaScriptAction(FPDF_DOCUMENT document, int index);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_javascript.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDoc_CloseJavaScriptAction), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFDoc_CloseJavaScriptAction(FPDF_JAVASCRIPT_ACTION javascript);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_javascript.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFJavaScriptAction_GetName), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFJavaScriptAction_GetName(FPDF_JAVASCRIPT_ACTION javascript, ref ushort buffer, uint buflen);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_javascript.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFJavaScriptAction_GetScript), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFJavaScriptAction_GetScript(FPDF_JAVASCRIPT_ACTION javascript, ref ushort buffer, uint buflen);
}