using System;
using System.Security;
using System.Runtime.InteropServices;
using PdfLibCore.Generated.Enums;
using PdfLibCore.Generated.Structs;
using PdfLibCore.Generated.Types;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY

namespace PdfLibCore.Generated;
public static partial class PlatformInvoke
{
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFBookmark_GetFirstChild), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_BOOKMARK FPDFBookmark_GetFirstChild(FPDF_DOCUMENT document, FPDF_BOOKMARK bookmark);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFBookmark_GetNextSibling), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_BOOKMARK FPDFBookmark_GetNextSibling(FPDF_DOCUMENT document, FPDF_BOOKMARK bookmark);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFBookmark_GetTitle), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFBookmark_GetTitle(FPDF_BOOKMARK bookmark, out IntPtr buffer, uint buflen);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFBookmark_Find), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_BOOKMARK FPDFBookmark_Find(FPDF_DOCUMENT document, FPDF_WIDESTRING title);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFBookmark_GetDest), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_DEST FPDFBookmark_GetDest(FPDF_DOCUMENT document, FPDF_BOOKMARK bookmark);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFBookmark_GetAction), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_ACTION FPDFBookmark_GetAction(FPDF_BOOKMARK bookmark);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAction_GetType), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFAction_GetType(FPDF_ACTION action);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAction_GetDest), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_DEST FPDFAction_GetDest(FPDF_DOCUMENT document, FPDF_ACTION action);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAction_GetFilePath), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFAction_GetFilePath(FPDF_ACTION action, out IntPtr buffer, uint buflen);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAction_GetURIPath), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFAction_GetURIPath(FPDF_DOCUMENT document, FPDF_ACTION action, out IntPtr buffer, uint buflen);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDest_GetDestPageIndex), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFDest_GetDestPageIndex(FPDF_DOCUMENT document, FPDF_DEST dest);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDest_GetView), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFDest_GetView(FPDF_DEST dest, out uint pNumParams, ref float pParams);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDest_GetLocationInPage), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFDest_GetLocationInPage(FPDF_DEST dest, ref int hasXVal, ref int hasYVal, ref int hasZoomVal, ref float x, ref float y, ref float zoom);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_GetLinkAtPoint), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_LINK FPDFLink_GetLinkAtPoint(FPDF_PAGE page, double x, double y);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_GetLinkZOrderAtPoint), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFLink_GetLinkZOrderAtPoint(FPDF_PAGE page, double x, double y);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_GetDest), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_DEST FPDFLink_GetDest(FPDF_DOCUMENT document, FPDF_LINK link);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_GetAction), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_ACTION FPDFLink_GetAction(FPDF_LINK link);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_Enumerate), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFLink_Enumerate(FPDF_PAGE page, out int start_pos, ref FPDF_LINK link_annot);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_GetAnnot), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_ANNOTATION FPDFLink_GetAnnot(FPDF_PAGE page, FPDF_LINK link_annot);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_GetAnnotRect), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFLink_GetAnnotRect(FPDF_LINK link_annot, ref FS_RECTF rect);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_CountQuadPoints), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFLink_CountQuadPoints(FPDF_LINK link_annot);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFLink_GetQuadPoints), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFLink_GetQuadPoints(FPDF_LINK link_annot, int quad_index, ref FS_QUADPOINTSF quad_points);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_GetPageAAction), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_ACTION FPDF_GetPageAAction(FPDF_PAGE page, int aa_type);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_GetFileIdentifier), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDF_GetFileIdentifier(FPDF_DOCUMENT document, FPDF_FILEIDTYPE id_type, out IntPtr buffer, uint buflen);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_GetMetaText), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDF_GetMetaText(FPDF_DOCUMENT document, FPDF_BYTESTRING tag, out IntPtr buffer, uint buflen);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_doc.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_GetPageLabel), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDF_GetPageLabel(FPDF_DOCUMENT document, int page_index, out IntPtr buffer, uint buflen);
}