using System;
using System.Security;
using System.Runtime.InteropServices;
using PdfLibCore.Generated.Enums;
using PdfLibCore.Generated.Structs;
using PdfLibCore.Generated.Types;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY

namespace PdfLibCore.Generated;
public static partial class PlatformInvoke
{
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDoc_GetAttachmentCount), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFDoc_GetAttachmentCount(FPDF_DOCUMENT document);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDoc_AddAttachment), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_ATTACHMENT FPDFDoc_AddAttachment(FPDF_DOCUMENT document, FPDF_WIDESTRING name);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDoc_GetAttachment), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_ATTACHMENT FPDFDoc_GetAttachment(FPDF_DOCUMENT document, int index);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFDoc_DeleteAttachment), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFDoc_DeleteAttachment(FPDF_DOCUMENT document, int index);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAttachment_GetName), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFAttachment_GetName(FPDF_ATTACHMENT attachment, ref ushort buffer, uint buflen);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAttachment_HasKey), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAttachment_HasKey(FPDF_ATTACHMENT attachment, FPDF_BYTESTRING key);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAttachment_GetValueType), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAttachment_GetValueType(FPDF_ATTACHMENT attachment, FPDF_BYTESTRING key);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAttachment_SetStringValue), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAttachment_SetStringValue(FPDF_ATTACHMENT attachment, FPDF_BYTESTRING key, FPDF_WIDESTRING value);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAttachment_GetStringValue), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern uint FPDFAttachment_GetStringValue(FPDF_ATTACHMENT attachment, FPDF_BYTESTRING key, ref ushort buffer, uint buflen);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAttachment_SetFile), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAttachment_SetFile(FPDF_ATTACHMENT attachment, FPDF_DOCUMENT document, ref IntPtr contents, uint len);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_attachment.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFAttachment_GetFile), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFAttachment_GetFile(FPDF_ATTACHMENT attachment, out IntPtr buffer, uint buflen, out uint out_buflen);
}