using System;
using System.Security;
using System.Runtime.InteropServices;
using PdfLibCore.Generated.Enums;
using PdfLibCore.Generated.Structs;
using PdfLibCore.Generated.Types;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY

namespace PdfLibCore.Generated;
public static partial class PlatformInvoke
{
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_SetMediaBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFPage_SetMediaBox(FPDF_PAGE page, float left, float bottom, float right, float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_SetCropBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFPage_SetCropBox(FPDF_PAGE page, float left, float bottom, float right, float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_SetBleedBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFPage_SetBleedBox(FPDF_PAGE page, float left, float bottom, float right, float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_SetTrimBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFPage_SetTrimBox(FPDF_PAGE page, float left, float bottom, float right, float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_SetArtBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFPage_SetArtBox(FPDF_PAGE page, float left, float bottom, float right, float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_GetMediaBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFPage_GetMediaBox(FPDF_PAGE page, out float left, out float bottom, out float right, out float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_GetCropBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFPage_GetCropBox(FPDF_PAGE page, out float left, out float bottom, out float right, out float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_GetBleedBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFPage_GetBleedBox(FPDF_PAGE page, out float left, out float bottom, out float right, out float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_GetTrimBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFPage_GetTrimBox(FPDF_PAGE page, out float left, out float bottom, out float right, out float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_GetArtBox), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFPage_GetArtBox(FPDF_PAGE page, out float left, out float bottom, out float right, out float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_TransFormWithClip), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFPage_TransFormWithClip(FPDF_PAGE page, ref FS_MATRIX matrix, ref FS_RECTF clipRect);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPageObj_TransformClipPath), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFPageObj_TransformClipPath(FPDF_PAGEOBJECT page_object, double a, double b, double c, double d, double e, double f);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPageObj_GetClipPath), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_CLIPPATH FPDFPageObj_GetClipPath(FPDF_PAGEOBJECT page_object);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFClipPath_CountPaths), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFClipPath_CountPaths(FPDF_CLIPPATH clip_path);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFClipPath_CountPathSegments), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern int FPDFClipPath_CountPathSegments(FPDF_CLIPPATH clip_path, int path_index);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFClipPath_GetPathSegment), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_PATHSEGMENT FPDFClipPath_GetPathSegment(FPDF_CLIPPATH clip_path, int path_index, int segment_index);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_CreateClipPath), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_CLIPPATH FPDF_CreateClipPath(float left, float bottom, float right, float top);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_DestroyClipPath), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDF_DestroyClipPath(FPDF_CLIPPATH clipPath);
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_transformpage.h.</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDFPage_InsertClipPath), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDFPage_InsertClipPath(FPDF_PAGE page, FPDF_CLIPPATH clipPath);
}