using System;
using System.Security;
using System.Runtime.InteropServices;
using PdfLibCore.Generated.Enums;
using PdfLibCore.Generated.Structs;
using PdfLibCore.Generated.Types;

/*
This file is part of PdfLibCore, a wrapper around the PDFium library for the .NET.
Inspired by the awesome work of PDFiumSharp by Tobias Meyer.

Copyright (C) 2023 J.C.A. Kokenberg & Jan Baarssen
License: Microsoft Reciprocal License (MS-RL)
*/

// AUTOGENERATED FILE - 10-05-2023 (01:50:33) - Utc
// DO NOT MODIFY

namespace PdfLibCore.Generated;
public static partial class PlatformInvoke
{
    ///<summary>
    /// Returns a pointer to the default character set to TT Font name map. The
    /// map is an array of FPDF_CharsetFontMap structs, with its end indicated
    /// by a { -1, NULL } entry.
    ///</summary>
    ///<remarks>For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_sysfontinfo.h.</remarks>
    ///<returns>Pointer to the Charset Font Map.</returns>
    [DllImport(DllName, EntryPoint = nameof(FPDF_GetDefaultTTFMap), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_CHARSETFONTMAP FPDF_GetDefaultTTFMap();
    ///<summary>Add a system font to the list in PDFium.</summary>
    ///<param name = "mapper">Opaque pointer to Foxit font mapper</param>
    ///<param name = "face">The font face name</param>
    ///<param name = "charset">Font character set. See above defined constants.</param>
    ///<remarks>
    /// This function is only called during the system font list building
    /// process.
    /// For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_sysfontinfo.h.
    ///</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_AddInstalledFont), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDF_AddInstalledFont(out IntPtr mapper, ref string face, int charset);
    ///<summary>Set the system font info interface into PDFium</summary>
    ///<param name = "pFontInfo">Pointer to a FPDF_SYSFONTINFO structure</param>
    ///<remarks>
    /// Platform support implementation should implement required methods of
    /// FFDF_SYSFONTINFO interface, then call this function during PDFium
    /// initialization process.
    /// For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_sysfontinfo.h.
    ///</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_SetSystemFontInfo), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDF_SetSystemFontInfo(ref FPDF_SYSFONTINFO pFontInfo);
    ///<summary>Get default system font info interface for current platform</summary>
    ///<remarks>
    /// For some platforms, PDFium implements a default version of system
    /// font info interface. The default implementation can be passed to
    /// FPDF_SetSystemFontInfo().
    /// For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_sysfontinfo.h.
    ///</remarks>
    ///<returns>
    /// Pointer to a FPDF_SYSFONTINFO structure describing the default
    /// interface, or NULL if the platform doesn't have a default interface.
    /// Application should call FPDF_FreeDefaultSystemFontInfo to free the
    /// returned pointer.
    ///</returns>
    [DllImport(DllName, EntryPoint = nameof(FPDF_GetDefaultSystemFontInfo), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern FPDF_SYSFONTINFO FPDF_GetDefaultSystemFontInfo();
    ///<summary>Free a default system font info interface</summary>
    ///<param name = "pFontInfo">Pointer to a FPDF_SYSFONTINFO structure</param>
    ///<remarks>
    /// This function should be called on the output from
    /// FPDF_SetSystemFontInfo() once it is no longer needed.
    /// For more information see: https://pdfium.googlesource.com/pdfium/+/master/public/fpdf_sysfontinfo.h.
    ///</remarks>
    [DllImport(DllName, EntryPoint = nameof(FPDF_FreeDefaultSystemFontInfo), SetLastError = true), SuppressUnmanagedCodeSecurity]
    public static extern IntPtr FPDF_FreeDefaultSystemFontInfo(ref FPDF_SYSFONTINFO pFontInfo);
}